### ISSUE TITLE
Which .py include RIFE-Large?

### ISSUE THREAD

**Issue by silenye** [hzwer/arXiv2021-RIFE#243]
Hi, I am so exciting about your work!
I want to know where is the RIFE-Large(2T2R)?
Thanks!

**Comment by hzwer** [comment]
Hi, I add the .py in https://github.com/hzwer/arXiv2021-RIFE/blob/main/model/IFNet_2R.py.
And in https://github.com/hzwer/arXiv2021-RIFE/blob/f8f415bd8e9a2808378038b7d53f6d518fc29501/model/RIFE.py#L56, we can set TTA=True to get 2T evaluation.

**Comment by hzwer** [comment]
Hi, I try 2 method to deal with the final upsample.1. TransposedConv->Conv2d 2. adjust the scale of bilinear upsample. They have similar effect.
RIFE is still in the development stage, I am not sure about the final implementation; but I try to keep the RIFE-baseline unchanged.

**Comment by silenye** [comment]
Thanks your reply!
Does 2T participate in training? I don't see the 2T operation on the image when loading the data.
:)

**Comment by hzwer** [comment]
@silenye No, 2T is just a test-time augmentation trick.

**Comment by chen-san** [comment]
@hzwer  Where can I download RIFE-Large checkpoint so I can evaluate it？

**Comment by hzwer** [comment]
@chen-san 
https://github.com/hzwer/arXiv2021-RIFE/tree/cd5366db61ae8cec1497be0f2d6167117968ab5a
There is a previous RIFE-Large model, it should produce 36.21dB on Vimeo90K benchmark.
For current version, I do not organize the relevant code and weights, because it may change at any time. Sorry for that.
